Update update-badge.yml

diff --git a/.github/workflows/update-badge.yml b/.github/workflows/update-badge.yml
--- a/.github/workflows/update-badge.yml
+++ b/.github/workflows/update-badge.yml
@@ -1,28 +1,39 @@
 name: Update User Count Badge
+
 on:
   schedule:
     - cron: '0 0 * * *'  
-  workflow_dispatch:    
+  workflow_dispatch:     
 
 jobs:
   update-badge:
     runs-on: ubuntu-latest
     permissions:
       contents: write
+    
     steps:
       - uses: actions/checkout@v4
+      
       - name: Check Number
         id: get-count
         run: |
-          COUNT=$(curl -s https://api.counterapi.dev/v1/sace-viewer/users | jq '.count')
+          COUNT=$(curl -sL "https://api.counterapi.dev/v1/sace-viewer/users/" | jq -r '.count')
+
+          if [ "$COUNT" == "null" ] || [ -z "$COUNT" ]; then
+            echo "Error: No number was obtained!"
+            exit 1
+          fi
+          
           echo "count=$COUNT" >> $GITHUB_OUTPUT
-      - name: Update README
+          echo "Number found: $COUNT"
+          
+      - name: Update Readme
         run: |
-          # README'deki "Users-ANYNUMBER-" kısmını bulur ve yeni sayıyla değiştirir
           sed -i "s/Users-[0-9]*-/Users-${{ steps.get-count.outputs.count }}-/" README.md
+          
       - name: Save and Push
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add README.md
-          git diff --quiet && git diff --staged --quiet || (git commit -m "📊 Kullanıcı sayısı güncellendi: ${{ steps.get-count.outputs.count }}" && git push)
+          git diff --quiet && git diff --staged --quiet || (git commit -m "📊 User count updated: ${{ steps.get-count.outputs.count }}" && git push)
